-- MySQL Script generated by MySQL Workbench
-- Sat Apr 11 20:13:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- EDIT: Manuel Stolze 
-- Aug 04 2021 23:26 

SET @OLD_UNIQUE_CHECKS=@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BrettSpiel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BrettSpiel` DEFAULT CHARACTER SET utf16 ;